package enums;

public enum TokenType {
    NUMBER, STRING, BOOL,
    LPARENT, RPARENT,
    LBRACE, RBRACE,
    SEMICOLON, ASSIGN, COMMA,
    PLUS, MINUS, MUL, DIV,
    IDENT,
    IF, ELSE, WHILE, FUNCTION, RETURN, CLASS,
    GREATER, LESS, EQUAL, GREATEREQUAL, LESSEQUAL, NOTEQUAL,
    AND, OR, NOT
}
