package enums;

public enum TokenType {
    NUMBER, STRING, BOOL,
    LPARENT, RPARENT,
    LBRACE, RBRACE,
    SEMICOLON, ASSIGN,
    PLUS, MINUS, MUL, DIV,
    IDENT, COMMENTARY,
    PRINT, IF, ELSE,
    GREATER, LESS, EQUAL, GREATEREQUAL, LESSEQUAL,
    AND, OR, NOT
}
