package enums;

public enum TokenType {
    NUMBER, STRING, BOOL,
    LPARENT, RPARENT,
    LBRACE, RBRACE,
    LBRACKET, RBRACKET,
    SEMICOLON, ASSIGN, COMMA, DOT,
    PLUS, MINUS, MUL, DIV,
    IDENT,
    IF, ELSE, WHILE, FUNCTION, RETURN, CLASS, NEW,
    GREATER, LESS, EQUAL, GREATEREQUAL, LESSEQUAL, NOTEQUAL, ARROW,
    AND, OR, NOT,
    EOF
}
